env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
plugins:
  - class-property
rules:
  indent:
    - 2
    - 4
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - never
  arrow-spacing:
    - 2
    - before: true
      after: true
  no-confusing-arrow: 2
  no-var: 2
  no-console: 0
  object-shorthand:
    - 2
    - methods
  prefer-arrow-callback: 2
  prefer-const: 1
  prefer-template: 1
